---
title: "Datos de felinos de Costa Rica"
author: "Juan Alberto Mora"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Librerías
```{r carga-paquetes, message=FALSE, echo=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(sf)
library(leaflet)
library(DT)
```

```{r directorio, echo=FALSE}
setwd("C:/Users/c15181/Practica felinos/Datos-de-felinos-de-Costa-Rica")

```


```{r datos, echo=FALSE}
felinos <-
  st_read(
    "C:/Users/c15181/Practica felinos/Datos-de-felinos-de-Costa-Rica/felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", # columna de longitud decimal
      "Y_POSSIBLE_NAMES=decimalLatitude"   # columna de latitud decimal
    ),
    quiet = TRUE
  )

provincias <-
  st_read(
    "C:/Users/c15181/Practica felinos/Datos-de-felinos-de-Costa-Rica/provincias.geojson",
    quiet = TRUE # para evitar el despliegue de mensajes
  )
```

## Tabla

```{r tabla, echo=FALSE}
felinos %>% dplyr::select(species,
                          eventDate,
                          stateProvince,
                          locality,
                          decimalLongitude,
                          decimalLatitude) %>% st_drop_geometry() %>% datatable(
                            colnames = c(
                              "Especie",
                              "Fecha",
                              "Provincia",
                              "Localidad",
                              "Longitud",
                              "Latitud"
                            ),
                            options = list(
                              pagelenght = 10,
                              language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
                            )
                          )
```

## Gráfico

```{r}
ggplot2_barras_conteo <-
  felinos %>%
  ggplot(aes(x = genus)) +
  geom_bar() +
  ggtitle("cantidad de felinos por especie") +
  xlab("Especie") +
  ylab("Cantidad") +
  theme_minimal()

ggplotly(ggplot2_barras_conteo) %>% config(locale = 'es')
```

## Mapa

```{r Mapa, echo=FALSE}
leaflet() %>%
  addTiles() %>% # capa base de OSM
  addPolygons( # capa de provincias (polígonos)
    data = provincias,
    color = "black",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 1.0,
  ) %>%  
  addCircleMarkers( # capa de registros de presencia (puntos)
    data = felinos,
    stroke = F,
    radius = 4,
    fillColor = 'blue',
    fillOpacity = 1
  )
```

